USE AdventureWorks2022
GO
--- SELECT * FROM [NOMBRE_TABLE]
SELECT * FROM [dbo].[DatabaseLog] 
--NUNCA HAGAN ESTO

-- SELECT columnas FROM Tabla
SELECT 
     [DatabaseLogID]
    , [Event]
    , [Schema]
FROM [DatabaseLog]

-- TOP - DISTINCT
SELECT  DISTINCT [Event] FROM [DatabaseLog]
--Event
--CREATE_XML_SCHEMA_COLLECTION
--CREATE_EXTENDED_PROPERTY
--CREATE_XML_INDEX
--CREATE_TRIGGER
--CREATE_TYPE
--CREATE_INDEX
--ALTER_TABLE
--CREATE_TABLE
--CREATE_PROCEDURE
--CREATE_VIEW
--CREATE_FULLTEXT_INDEX
--CREATE_FUNCTION
--CREATE_FULLTEXT_CATALOG
--CREATE_SCHEMA
--ALTER_XML_SCHEMA_COLLECTION


SELECT*FROM [DatabaseLog]
WHERE [Event] IN ('CREATE_TYPE','CREATE_VIEW','CREATE_PROCEDURE')